apiVersion: v2
name: test-umbrella
description: A Helm chart for testing purposes
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: common
    repository: file://./charts/common
    version: "1.0.0"
  - name: backend
    repository: file://./charts/backend
    version: "1.0.0"
  - name: frontend
    repository: file://./charts/frontend
    version: "1.0.0"
