apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://nemerosa.github.io/tmp-argo
    chart: umbrella
    targetRevision: 1.0.6
    helm:
      releaseName: "umbrella"
      values: |
        common:
          version: "1.0"
        backend:
          image:
            tag: "3.16"
        frontend:
          image:
            tag: "3.16"
  destination:
    server: https://kubernetes.default.svc
    namespace: test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
