apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://nemerosa.github.io/tmp-argo
    chart: common
    targetRevision: 1.0.1
    helm:
      releaseName: "common"
      values: |
        version: "0.1"
  destination:
    server: https://kubernetes.default.svc
    namespace: test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
