apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://nemerosa.github.io/tmp-argo
    chart: umbrella
    targetRevision: 1.1.0
    helm:
      releaseName: "umbrella"
      values: |
        backend:
          common:
            version: "1.1"
          image:
            tag: "1.21"
        frontend:
          common:
            version: "1.2"
          image:
            tag: "1.22"
  destination:
    server: https://kubernetes.default.svc
    namespace: test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
