apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nemerosa/tmp-argo.git
    targetRevision: main
    path: charts/umbrella
    helm:
      releaseName: "umbrella"
      valuesObject:
        common:
          version: "1.0"
        backend:
          image:
            tag: "3.15"
        frontend:
          image:
            tag: "3.15"
  destination:
    server: https://kubernetes.default.svc
    namespace: test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
